### ISSUE TITLE
Cannot be started on Linux

### ISSUE THREAD

**Issue by kovadam69** [quippy-git/javamod#5]
On linux there is immediatelly an exception when starting the program:

Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
	at java.desktop/java.awt.SystemTray.getSystemTray(SystemTray.java:180)
	at de.quippy.javamod.main.gui.MainForm.getTrayIcon(Unknown Source)
	at de.quippy.javamod.main.gui.MainForm.initialize(Unknown Source)
	at de.quippy.javamod.main.gui.MainForm.<init>(Unknown Source)
	at de.quippy.javamod.main.JavaMod$1.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

May be the system tray is not essential for the software to run?

**Comment by quippy-git** [comment]
I am sorry, that I did not test JavaMod on a WindowManager that does not have system tray support. There is indeed an error, I never happened to come across - as I never really tested it. It is already fixed - in my local version. I will make a new release 3.7.1 for that, because it's a critical error.

I had hoped, that this would not really affect any users nowadays... New release coming up...

**Comment by kovadam69** [comment]
Wow, thanks for the quick reply. I use Cinnamon desktop, it has system tray support, seems openjdk and Cinnamon does not have something common in communication :) I use OpenJDK 19.0.1.

I downloaded the sources, fixed it also, but now I have issues to load an amiga mod file, I get exception when I start the playback.
The mod file is from an amiga game.

Starting playback did not succeed!
java.lang.ArrayIndexOutOfBoundsException: Index -24 out of bounds for length 72
	at de.quippy.javamod.multimedia.mod.mixer.BasicModMixer.getFineTunePeriod(BasicModMixer.java:753)
	at de.quippy.javamod.multimedia.mod.mixer.BasicModMixer.getFineTunePeriod(BasicModMixer.java:797)
	at de.quippy.javamod.multimedia.mod.mixer.BasicModMixer.setNewInstrumentAndPeriod(BasicModMixer.java:1930)
	at de.quippy.javamod.multimedia.mod.mixer.BasicModMixer.doRowEvents(BasicModMixer.java:2094)
	at de.quippy.javamod.multimedia.mod.mixer.BasicModMixer.doRowAndTickEvents(BasicModMixer.java:2211)
	at de.quippy.javamod.multimedia.mod.mixer.BasicModMixer.getLengthInMilliseconds(BasicModMixer.java:649)
	at de.quippy.javamod.multimedia.mod.ModMixer.getLengthInMilliseconds(ModMixer.java:404)
	at de.quippy.javamod.main.gui.components.SeekBarPanel.setCurrentMixer(SeekBarPanel.java:297)
	at de.quippy.javamod.main.gui.MainForm.createNewMixer(MainForm.java:2979)
	at de.quippy.javamod.main.gui.MainForm.doStartPlaying(MainForm.java:2835)
	at de.quippy.javamod.main.gui.MainForm.doStartPlaying(MainForm.java:2812)
	at de.quippy.javamod.main.gui.MainForm$29.actionPerformed(MainForm.java:2102)

**Comment by quippy-git** [comment]
Please provide me that mod. There is obviously something special in that one I yet did not come across. Send it to my mail address  - that would be the simplest.

**Comment by quippy-git** [comment]
I took a look into those mods. ModPlug cannot open them, Schism cannot open them - and what I can see so far is, that these are unsupported mods. I have no idea, *what* it is... I assume, it is something special created only for that game. I will look a bit deeper into it, but I cannot promise anything.

**Comment by kovadam69** [comment]
Ok, thank you. But dont put any time into it, unless you have some free
time for it..It's not a big deal if its nor working

Daniel Becker ***@***.***> ezt írta (időpont: 2023. dec. 14.,
Csü 18:22):

**Comment by quippy-git** [comment]
The new update is there. I found out that your game mods are basically ProTracker mods (31 samples, 4 channels) but with delta stored samples. Mod ID is "!PM!" - whatever tracker that is... 
But they sound right to me.

I close this one then.

**Comment by kovadam69** [comment]
Awsome work! Thank you very much! :)

Daniel Becker ***@***.***> ezt írta (időpont: 2023. dec. 14.,
Cs, 21:33):
